### PR TITLE
Make the template values selection more interactive

### PR DESCRIPTION
**Pull request by ffevotte**
This PR makes the selection of templates parameters more interactive. Git-config is used to retrieve default values, which are then interactively proposed to be validated (or amended) by the user. A final confirmation is asked before going on with the project configuration as usual.

```julia
julia> PkgSkeleton.generate("Foo")
[ Info: getting template values
Confirm default values by pressing RETURN, or enter a customized value
Author name (John Doe)>
Author email (johndoe@gmail.com)> john.doe@example.com
Github user name ()> jdoe
Copyright year (2019)> 
┌ Info: parameters:
│   {UUID} = UUID("1a7ac041-bdf1-4da1-9e3a-91f6f6c88e92")
│   {PKGNAME} = "Foo"
│   {USERNAME} = "John Doe"
│   {USEREMAIL} = "john.doe@example.com"
│   {GHUSER} = "jdoe"
└   {YEAR} = 2019
Confirm (Y)> 
[ Info: copy and substitute
...
```

My use case for this is that on my home computer, I can't set up a global git-config identity: depending on which project I work on, I use either my personal email address or my professional one.

I'm not sure this PR is entirely in line with what you had in mind, though. Please feel free to comment / criticize / reject it!

And, as always, thank you for your work on this!

### CODE REVIEW

**Comment by tpapp** [comment]
I think that allowing customization would make sense, but I would prefer that to happen as arguments to `PkgSkeleton.generate` instead of an interactive prompt.

**Comment by ffevotte** [comment]
Well, it's entirely up to you!

And what about arguments to `PkgSkeleton.generate`, alongside a new entry point (perhaps `PkgSkeleton.interactive()`) that would interactively prompt for values before calling `generate`?

**Comment by tpapp** [comment]
Sorry, I would prefer to avoid interactive prompts if possible; they are quite hard to unit test and I think that just providing keyword arguments would serve a similar purpose.

**Comment by tpapp** [comment]
I implemented more customizations in #21. With that API, you can do
```julia
import PkgSkeleton
# you can also prompt for these interactively
replacements = (GHUSER = "jdoe", USERNAME = "John Doe")
PkgSkeleton.generate("/path/to/SomePackage.jl"; replacements = replacements)
```
I am sorry that I am reluctant to include interactive prompts in this package, but they really complicate code and testing.

I am closing this in favor of that PR, thanks for the suggestion.

**Pull request closed without merging**
