### PR TITLE
ask the user to complete their git config

### PR DESCRIPTION
**Pull request by francescoalemanno**
Hi Tamas,

i wanted to use your package and as soon as i tried it i got:

```julia
julia> PkgSkeleton.generate("MyPackage")
[ Info: getting template values
ERROR: GitError(Code:ENOTFOUND, Class:Config, config value 'github.user' was not found)
.......
```

I think it could be handy to ask the user to supply the info if the info is lacking
Btw very nice package, super minimalistic and it does it's job really well

### CODE REVIEW

**Comment by francescoalemanno** [comment]
it is kinda hard to add a test for the functionality i'd like to add

**Comment by tpapp** [comment]
Yes, this is why I am against interactive prompts in this package (cf #12).

Would a more informative error message fix this issue for you? I guess that in any case, I think it is reasonable for users to set `github.user` if they are otherwise using Github.

**Comment by francescoalemanno** [comment]
Yes, a GOOD error message suggesting the solution would be perfect
i have a proposal:
1) modify getgitopt to leave the replacement at nothing, is there is no parameter available and no global config
2) inside generate check for nothings, if a "nothing" is present tell the user they lack such config in their system and suggest the call syntax for PkgSkeleton.generate

maybe this is acceptable: https://github.com/tpapp/PkgSkeleton.jl/pull/23/commits/8f3488c9eec6c94e5850d670fcea4742b327867f

i did not add any testing for now, but this modification can be tested for sure,

**Comment by tpapp** [comment]
Closing in favor of #24, I hope that solves the issue for you.

**Pull request closed without merging**
